spring:
  config:
    activate:
      on-profile: dev

  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/test;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: 1234
      driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  security:
    user:
      name: user
      password: 1234


  # 스웨거 설정
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

auth:
  allowIp: 127.8.8.8,1.2.3.4,127.0.0.1

logging:
  logback:
    rollingpolicy:
      max-history: 3
      max-file-size: 10MB
    path: "./logs/api/dev"
  level:
    root: INFO
  slack:
    webhook-uri: https://hooks.slack.com/services/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
  config:
    classpath: logback-spring.xml

slack:
  token: xoxb-3971347691442-4482065644323-CmhiHVZfCblWzhEeDq0GOTtk
  channel:
    monitor: '#web-monitor'

server:
  shutdown: graceful

jwt:
  secret-key: ZGFvdS10ZXN0LWp3dC1hdXRoZW50aWZpY2F0aW9uLXVzZXItb25seS1wYXNzLWF1dGgtcGxlYXNlLWdvLXdsbC1wbGVhc2UtMjM1aHMK
  ACCESS_TOKEN_EXPIRE_SEC: 3600000   # 1 hour
  refresh-token-expire-sec: 86400000  # 1 day