spring:
  config:
    activate:
      on-profile: real

  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/test;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: 1234
      driver-class-name: org.h2.Driver

  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        default_batch_fetch_size: 1000

  batch:
    job:
      names: ${job.name:NONE}

logging:
  logback:
    rollingpolicy:
      max-history: 30
      max-file-size: 100MB
    path: "./logs/batch/real"
  level:
    root: INFO
  slack:
    webhook-uri: https://hooks.slack.com/services/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
  config:
    classpath: logback-spring.xml

slack:
  token: xoxb-3971347691442-4482065644323-CmhiHVZfCblWzhEeDq0GOTtk
  channel:
    monitor: '#batch_monitor'

batch:
  input:
    path: './data'
  absolute:
    path: 'batch/src/main/resources/data'