spring:
  config:
    activate:
      on-profile: test

  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/test;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: 1234
      driver-class-name: org.h2.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000

  sql:
    init:
      mode: always
      schema-locations: classpath:db/local/schema.sql

  batch:
    job:
      names: ${job.name:NONE}

logging:
  logback:
    rollingpolicy:
      max-history: 3
      max-file-size: 1MB
    path: "./logs/batch/test"
  level:
    root: INFO
  slack:
    webhook-uri: https://hooks.slack.com/services/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
  config:
    classpath: logback-spring.xml

slack:
  token: xoxb-3971347691442-4482065644323-CmhiHVZfCblWzhEeDq0GOTtk
  channel:
    monitor: '#batch_monitor'

batch:
  input:
    path: './data/testData'
  absolute:
    path: 'src/test/data/'